// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDepGz9RXho5oyLpT08cEqkYidOvfU6m6s',
    appId: '1:1026872298942:web:e10439ad6c8ccf49d0fdef',
    messagingSenderId: '1026872298942',
    projectId: 'quadrasports-1232e',
    authDomain: 'quadrasports-1232e.firebaseapp.com',
    storageBucket: 'quadrasports-1232e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvMRj5k9r9uOveFREd9ifn6a56fDITbfQ',
    appId: '1:1026872298942:android:15d6959b699b45fbd0fdef',
    messagingSenderId: '1026872298942',
    projectId: 'quadrasports-1232e',
    storageBucket: 'quadrasports-1232e.appspot.com',
  );
}
